apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrafy-deployment
  labels:
    app: infrafy
  namespace: infrafy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: infrafy
  template:
    metadata:
      labels:
        app: infrafy
    spec:
      containers:
        - name: infrafy
          image: ericbsantana/infrafy:ff16170
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: infrafy-env
                  key: port
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: db
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi
