apiVersion: v1
kind: Service

metadata:
  name: infrafy-service
  labels:
    app: infrafy
  namespace: infrafy

spec:
  selector:
    app: infrafy
  type: ClusterIP
  ports:
    - name: infrafy-service
      protocol: TCP
      port: 8080
      targetPort: 8080
